using System;
using System.Collections.Generic;
using System.Linq;

namespace AtomicCipher
{
   public static class Elements
   {
      private static List<Models.Element> _elements = new()
      {
         new Models.Element() { Number = 1, Symbol = "H", Name = "Hydrogen" },
         new Models.Element() { Number = 2, Symbol = "He", Name = "Helium" },
         new Models.Element() { Number = 3, Symbol = "Li", Name = "Lithium" },
         new Models.Element() { Number = 4, Symbol = "Be", Name = "Beryllium" },
         new Models.Element() { Number = 5, Symbol = "B", Name = "Boron" },
         new Models.Element() { Number = 6, Symbol = "C", Name = "Carbon" },
         new Models.Element() { Number = 7, Symbol = "N", Name = "Nitrogen" },
         new Models.Element() { Number = 8, Symbol = "O", Name = "Oxygen" },
         new Models.Element() { Number = 9, Symbol = "F", Name = "Fluorine" },
         new Models.Element() { Number = 10, Symbol = "Ne", Name = "Neon" },
         new Models.Element() { Number = 11, Symbol = "Na", Name = "Sodium" },
         new Models.Element() { Number = 12, Symbol = "Mg", Name = "Magnesium" },
         new Models.Element() { Number = 13, Symbol = "Al", Name = "Aluminum" },
         new Models.Element() { Number = 14, Symbol = "Si", Name = "Silicon" },
         new Models.Element() { Number = 15, Symbol = "P", Name = "Phosphorus" },
         new Models.Element() { Number = 16, Symbol = "S", Name = "Sulfur" },
         new Models.Element() { Number = 17, Symbol = "Cl", Name = "Chlorine" },
         new Models.Element() { Number = 18, Symbol = "Ar", Name = "Argon" },
         new Models.Element() { Number = 19, Symbol = "K", Name = "Potassium" },
         new Models.Element() { Number = 20, Symbol = "Ca", Name = "Calcium" },
         new Models.Element() { Number = 21, Symbol = "Sc", Name = "Scandium" },
         new Models.Element() { Number = 22, Symbol = "Ti", Name = "Titanium" },
         new Models.Element() { Number = 23, Symbol = "V", Name = "Vanadium" },
         new Models.Element() { Number = 24, Symbol = "Cr", Name = "Chromium" },
         new Models.Element() { Number = 25, Symbol = "Mn", Name = "Manganese" },
         new Models.Element() { Number = 26, Symbol = "Fe", Name = "Iron" },
         new Models.Element() { Number = 27, Symbol = "Co", Name = "Cobalt" },
         new Models.Element() { Number = 28, Symbol = "Ni", Name = "Nickel" },
         new Models.Element() { Number = 29, Symbol = "Cu", Name = "Copper" },
         new Models.Element() { Number = 30, Symbol = "Zn", Name = "Zinc" },
         new Models.Element() { Number = 31, Symbol = "Ga", Name = "Gallium" },
         new Models.Element() { Number = 32, Symbol = "Ge", Name = "Germanium" },
         new Models.Element() { Number = 33, Symbol = "As", Name = "Arsenic" },
         new Models.Element() { Number = 34, Symbol = "Se", Name = "Selenium" },
         new Models.Element() { Number = 35, Symbol = "Br", Name = "Bromine" },
         new Models.Element() { Number = 36, Symbol = "Kr", Name = "Krypton" },
         new Models.Element() { Number = 37, Symbol = "Rb", Name = "Rubidium" },
         new Models.Element() { Number = 38, Symbol = "Sr", Name = "Strontium" },
         new Models.Element() { Number = 39, Symbol = "Y", Name = "Yttrium" },
         new Models.Element() { Number = 40, Symbol = "Zr", Name = "Zirconium" },
         new Models.Element() { Number = 41, Symbol = "Nb", Name = "Niobium" },
         new Models.Element() { Number = 42, Symbol = "Mo", Name = "Molybdenum" },
         new Models.Element() { Number = 43, Symbol = "Tc", Name = "Technetium" },
         new Models.Element() { Number = 44, Symbol = "Ru", Name = "Ruthenium" },
         new Models.Element() { Number = 45, Symbol = "Rh", Name = "Rhodium" },
         new Models.Element() { Number = 46, Symbol = "Pd", Name = "Palladium" },
         new Models.Element() { Number = 47, Symbol = "Ag", Name = "Silver" },
         new Models.Element() { Number = 48, Symbol = "Cd", Name = "Cadmium" },
         new Models.Element() { Number = 49, Symbol = "In", Name = "Indium" },
         new Models.Element() { Number = 50, Symbol = "Sn", Name = "Tin" },
         new Models.Element() { Number = 51, Symbol = "Sb", Name = "Antimony" },
         new Models.Element() { Number = 52, Symbol = "Te", Name = "Tellurium" },
         new Models.Element() { Number = 53, Symbol = "I", Name = "Iodine" },
         new Models.Element() { Number = 54, Symbol = "Xe", Name = "Xenon" },
         new Models.Element() { Number = 55, Symbol = "Cs", Name = "Cesium" },
         new Models.Element() { Number = 56, Symbol = "Ba", Name = "Barium" },
         new Models.Element() { Number = 57, Symbol = "La", Name = "Lanthanum" },
         new Models.Element() { Number = 58, Symbol = "Ce", Name = "Cerium" },
         new Models.Element() { Number = 59, Symbol = "Pr", Name = "Praseodymium" },
         new Models.Element() { Number = 60, Symbol = "Nd", Name = "Neodymium" },
         new Models.Element() { Number = 61, Symbol = "Pm", Name = "Promethium" },
         new Models.Element() { Number = 62, Symbol = "Sm", Name = "Samarium" },
         new Models.Element() { Number = 63, Symbol = "Eu", Name = "Europium" },
         new Models.Element() { Number = 64, Symbol = "Gd", Name = "Gadolinium" },
         new Models.Element() { Number = 65, Symbol = "Tb", Name = "Terbium" },
         new Models.Element() { Number = 66, Symbol = "Dy", Name = "Dysprosium" },
         new Models.Element() { Number = 67, Symbol = "Ho", Name = "Holmium" },
         new Models.Element() { Number = 68, Symbol = "Er", Name = "Erbium" },
         new Models.Element() { Number = 69, Symbol = "Tm", Name = "Thulium" },
         new Models.Element() { Number = 70, Symbol = "Yb", Name = "Ytterbium" },
         new Models.Element() { Number = 71, Symbol = "Lu", Name = "Lutetium" },
         new Models.Element() { Number = 72, Symbol = "Hf", Name = "Hafnium" },
         new Models.Element() { Number = 73, Symbol = "Ta", Name = "Tantalum" },
         new Models.Element() { Number = 74, Symbol = "W", Name = "Tungsten" },
         new Models.Element() { Number = 75, Symbol = "Re", Name = "Rhenium" },
         new Models.Element() { Number = 76, Symbol = "Os", Name = "Osmium" },
         new Models.Element() { Number = 77, Symbol = "Ir", Name = "Iridium" },
         new Models.Element() { Number = 78, Symbol = "Pt", Name = "Platinum" },
         new Models.Element() { Number = 79, Symbol = "Au", Name = "Gold" },
         new Models.Element() { Number = 80, Symbol = "Hg", Name = "Mercury" },
         new Models.Element() { Number = 81, Symbol = "Tl", Name = "Thallium" },
         new Models.Element() { Number = 82, Symbol = "Pb", Name = "Lead" },
         new Models.Element() { Number = 83, Symbol = "Bi", Name = "Bismuth" },
         new Models.Element() { Number = 84, Symbol = "Po", Name = "Polonium" },
         new Models.Element() { Number = 85, Symbol = "At", Name = "Astatine" },
         new Models.Element() { Number = 86, Symbol = "Rn", Name = "Radon" },
         new Models.Element() { Number = 87, Symbol = "Fr", Name = "Francium" },
         new Models.Element() { Number = 88, Symbol = "Ra", Name = "Radium" },
         new Models.Element() { Number = 89, Symbol = "Ac", Name = "Actinium" },
         new Models.Element() { Number = 90, Symbol = "Th", Name = "Thorium" },
         new Models.Element() { Number = 91, Symbol = "Pa", Name = "Protactinium" },
         new Models.Element() { Number = 92, Symbol = "U", Name = "Uranium" },
         new Models.Element() { Number = 93, Symbol = "Np", Name = "Neptunium" },
         new Models.Element() { Number = 94, Symbol = "Pu", Name = "Plutonium" },
         new Models.Element() { Number = 95, Symbol = "Am", Name = "Americium" },
         new Models.Element() { Number = 96, Symbol = "Cm", Name = "Curium" },
         new Models.Element() { Number = 97, Symbol = "Bk", Name = "Berkelium" },
         new Models.Element() { Number = 98, Symbol = "Cf", Name = "Californium" },
         new Models.Element() { Number = 99, Symbol = "Es", Name = "Einsteinium" },
         new Models.Element() { Number = 100, Symbol = "Fm", Name = "Fermium" },
         new Models.Element() { Number = 101, Symbol = "Md", Name = "Mendelevium" },
         new Models.Element() { Number = 102, Symbol = "No", Name = "Nobelium" },
         new Models.Element() { Number = 103, Symbol = "Lr", Name = "Lawrencium" },
         new Models.Element() { Number = 104, Symbol = "Rf", Name = "Rutherfordium" },
         new Models.Element() { Number = 105, Symbol = "Db", Name = "Dubnium" },
         new Models.Element() { Number = 106, Symbol = "Sg", Name = "Seaborgium" },
         new Models.Element() { Number = 107, Symbol = "Bh", Name = "Bohrium" },
         new Models.Element() { Number = 108, Symbol = "Hs", Name = "Hassium" },
         new Models.Element() { Number = 109, Symbol = "Mt", Name = "Meitnerium" },
         new Models.Element() { Number = 110, Symbol = "Ds", Name = "Darmstadtium" },
         new Models.Element() { Number = 111, Symbol = "Rg", Name = "Roentgenium" },
         new Models.Element() { Number = 112, Symbol = "Cn", Name = "Copernicium" },
         new Models.Element() { Number = 113, Symbol = "Nh", Name = "Nihonium" },
         new Models.Element() { Number = 114, Symbol = "Fl", Name = "Flerovium" },
         new Models.Element() { Number = 115, Symbol = "Mc", Name = "Moscovium" },
         new Models.Element() { Number = 116, Symbol = "Lv", Name = "Livermorium" },
         new Models.Element() { Number = 117, Symbol = "Ts", Name = "Tennessine" },
         new Models.Element() { Number = 118, Symbol = "Og", Name = "Oganesson" },
      };

      public static Models.Element GetElementByNumber(ushort elementNumber) =>
         _elements.FirstOrDefault(e => e.Number == elementNumber);

      public static Models.Element GetElementBySymbol(string elementSymbol) =>
         _elements.FirstOrDefault(e => String.Equals(e.Symbol, elementSymbol, StringComparison.OrdinalIgnoreCase));
      
      public static List<Models.Element> GetElementsBySymbolSearch(string q) =>
         _elements.Where(e => e.Symbol.Contains(q, StringComparison.OrdinalIgnoreCase)).ToList();
   }
}